---
javascripts:
- base:
  - jrails
  - application
  - yoga
  - image_swap
  - jqModal/jqModal
  - jquery.form
  - jquery.defaultvalue
  - jquery.jcarousel
  - jquery.validate
  - billing
  - home
  - login
  - shopping_cart
  - story
  - registration
  - yoga/registration
  - jquery.metadata
  - jquery.rating
  - jquery.scrollTo
- dev:
  - jquery
  - jquery-ui

stylesheets:
- base:
  - yoga_main
  - yoga_type
  - main
  - jqModal/jqModal
  - jquery.jcarousel
  - yoga_carousel_skin
  - ambassador
- admin:
  - admin
