# Used for subscription emails (subscription_notifier.rb)
app_name: YogaToday
from_email: info@yogatoday.com

# Used in account creation (account.rb)
base_domain: example.com

# Set this to true if you want to require CC info when creating a trial account for a paid plan
require_payment_info_for_trials: false

bug_recipients: ['bugs@yogatoday.com']

# Credit card gateway: One of brain_tree, authorize_net_cim, payment_express, or trust_commerce

development:
  #gateway: authorize_net_cim
  gateway: bogus
test:
  gateway: bogus
cucumber:
  gateway: bogus
staging:
  gateway: bogus
production:
  gateway: authorize_net_cim

